from .grades import GradeModule
from .schedule import ScheduleModule
from .exams import ExamModule
from .notifications import NotificationModule
from .courses import CourseModule
from .academic import AcademicModule
from .homepage import HomepageModule
from .evaluation import EvaluationModule
from .textbooks import TextbookModule
from .system import SystemModule
from .teaching_plan import TeachingPlanModule
